name: build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: install toolchain
        run: sudo apt install -y g++-11

      - name: make build directory
        run: mkdir ${{github.workspace}}/build && cd ${{github.workspace}}/build

      - name: configure cmake
        env:
          CXX: g++-11
        run: cmake ..

      - name: build
        run: cmake --build .

      - name: run tests
        run: ./test/crutch_test